services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      target: final
    ports:
      - "5027:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=eventos_db;User=root;Password=${MYSQL_ROOT_PASSWORD};
      - Jwt__Key=${JWT_KEY}
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    volumes:
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - cert_data:/app/cert
    depends_on:
      - db
    networks:
      - eventos_network
    entrypoint: ["dotnet", "EventosAPI.API.dll"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - eventos_network

  db:
    image: mysql:8.0
    container_name: eventos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: eventos_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eventos_network

  adminer:
    image: adminer
    container_name: eventos_adminer
    ports:
      - "8080:8080"
    networks:
      - eventos_network
    depends_on:
      - db

volumes:
  mysql_data:
  cert_data:

networks:
  eventos_network:
    name: eventos_network
    driver: bridge
